version: 2

project_name: cli-tools

release:
  prerelease: auto
  draft: true
  name_template: "CLI Tools {{.Version}}"

env:
  - CGO_ENABLED=0

before:
  hooks:
    - go mod tidy

builds:

- id: ebook-cli
  goos: [linux, windows]
  goarch: [amd64]
  binary: ebook-cli
  main: ./cmd/ebook
  ldflags:
    - -s -w -X github.com/dpurge/cli-tools/pkg/version.Version={{.Version}}

- id: flashcard-cli
  goos: [linux, windows]
  goarch: [amd64]
  binary: flashcard-cli
  main: ./cmd/flashcard
  ldflags:
    - -s -w -X github.com/dpurge/cli-tools/pkg/version.Version={{.Version}}

- id: scanbook-cli
  goos: [linux, windows]
  goarch: [amd64]
  binary: scanbook-cli
  main: ./cmd/scanbook
  ldflags:
    - -s -w -X github.com/dpurge/cli-tools/pkg/version.Version={{.Version}}

# dockers_v2:
# - images:
#   - "dpurge/cli-tools"

archives:
  - formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip

changelog:
  sort: asc