FROM mcr.microsoft.com/devcontainers/go:1.21

# RUN echo 'deb [trusted=yes] https://repo.goreleaser.com/apt/ /' | tee /etc/apt/sources.list.d/goreleaser.list \
#     && apt update \
#     && apt install goreleaser
    